import { sets as manualSets } from "./sets.manual";

export interface PokemonSet {
  slug: string;
  name: string;
  series: string;
  totalCards: number;
  releaseDate: string;
  logo: string;
  symbol: string;
}

const generatedSets: Record<string, PokemonSet> = {
  "jungle": {
    slug: "jungle",
    name: "Jungle",
    series: "base-series",
    totalCards: 64,
    releaseDate: "1999/06/16",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "fossil": {
    slug: "fossil",
    name: "Fossil",
    series: "base-series",
    totalCards: 62,
    releaseDate: "1999/10/10",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "base-set-2": {
    slug: "base-set-2",
    name: "Base Set 2",
    series: "base-series",
    totalCards: 130,
    releaseDate: "2000/02/24",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "team-rocket": {
    slug: "team-rocket",
    name: "Team Rocket",
    series: "base-series",
    totalCards: 83,
    releaseDate: "2000/04/24",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "legendary-collection": {
    slug: "legendary-collection",
    name: "Legendary Collection",
    series: "base-series",
    totalCards: 110,
    releaseDate: "2002/05/24",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "gym-heroes": {
    slug: "gym-heroes",
    name: "Gym Heroes",
    series: "gym-series",
    totalCards: 132,
    releaseDate: "2000/08/14",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "gym-challenge": {
    slug: "gym-challenge",
    name: "Gym Challenge",
    series: "gym-series",
    totalCards: 132,
    releaseDate: "2000/10/16",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "neo-genesis": {
    slug: "neo-genesis",
    name: "Neo Genesis",
    series: "neo-series",
    totalCards: 111,
    releaseDate: "2000/12/16",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "neo-discovery": {
    slug: "neo-discovery",
    name: "Neo Discovery",
    series: "neo-series",
    totalCards: 75,
    releaseDate: "2001/06/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "neo-revelation": {
    slug: "neo-revelation",
    name: "Neo Revelation",
    series: "neo-series",
    totalCards: 66,
    releaseDate: "2001/09/21",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "neo-destiny": {
    slug: "neo-destiny",
    name: "Neo Destiny",
    series: "neo-series",
    totalCards: 113,
    releaseDate: "2002/02/28",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "expedition-base-set": {
    slug: "expedition-base-set",
    name: "Expedition Base Set",
    series: "e-card",
    totalCards: 165,
    releaseDate: "2002/09/15",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "aquapolis": {
    slug: "aquapolis",
    name: "Aquapolis",
    series: "e-card",
    totalCards: 182,
    releaseDate: "2003/01/15",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "skyridge": {
    slug: "skyridge",
    name: "Skyridge",
    series: "e-card",
    totalCards: 182,
    releaseDate: "2003/05/12",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "ruby-sapphire": {
    slug: "ruby-sapphire",
    name: "Ruby & Sapphire",
    series: "ex-series",
    totalCards: 109,
    releaseDate: "2003/07/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "sandstorm": {
    slug: "sandstorm",
    name: "Sandstorm",
    series: "ex-series",
    totalCards: 100,
    releaseDate: "2003/09/18",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "dragon": {
    slug: "dragon",
    name: "Dragon",
    series: "ex-series",
    totalCards: 100,
    releaseDate: "2003/11/24",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "magma-vs-aqua": {
    slug: "magma-vs-aqua",
    name: "Team Magma vs Team Aqua",
    series: "ex-series",
    totalCards: 97,
    releaseDate: "2004/03/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "hidden-legends": {
    slug: "hidden-legends",
    name: "Hidden Legends",
    series: "ex-series",
    totalCards: 102,
    releaseDate: "2004/06/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "firered-leafgreen": {
    slug: "firered-leafgreen",
    name: "FireRed & LeafGreen",
    series: "ex-series",
    totalCards: 116,
    releaseDate: "2004/09/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "team-rocket-returns": {
    slug: "team-rocket-returns",
    name: "Team Rocket Returns",
    series: "ex-series",
    totalCards: 111,
    releaseDate: "2004/11/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "deoxys": {
    slug: "deoxys",
    name: "Deoxys",
    series: "ex-series",
    totalCards: 108,
    releaseDate: "2005/02/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "emerald": {
    slug: "emerald",
    name: "Emerald",
    series: "ex-series",
    totalCards: 107,
    releaseDate: "2005/05/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "unseen-forces": {
    slug: "unseen-forces",
    name: "Unseen Forces",
    series: "ex-series",
    totalCards: 145,
    releaseDate: "2005/08/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "delta-species": {
    slug: "delta-species",
    name: "Delta Species",
    series: "ex-series",
    totalCards: 114,
    releaseDate: "2005/10/31",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "legend-maker": {
    slug: "legend-maker",
    name: "Legend Maker",
    series: "ex-series",
    totalCards: 93,
    releaseDate: "2006/02/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "holon-phantoms": {
    slug: "holon-phantoms",
    name: "Holon Phantoms",
    series: "ex-series",
    totalCards: 111,
    releaseDate: "2006/05/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "crystal-guardians": {
    slug: "crystal-guardians",
    name: "Crystal Guardians",
    series: "ex-series",
    totalCards: 100,
    releaseDate: "2006/08/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "dragon-frontiers": {
    slug: "dragon-frontiers",
    name: "Dragon Frontiers",
    series: "ex-series",
    totalCards: 101,
    releaseDate: "2006/11/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "power-keepers": {
    slug: "power-keepers",
    name: "Power Keepers",
    series: "ex-series",
    totalCards: 108,
    releaseDate: "2007/02/02",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "diamond-pearl-base": {
    slug: "diamond-pearl-base",
    name: "Diamond & Pearl",
    series: "diamond-pearl",
    totalCards: 130,
    releaseDate: "2007/05/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "mysterious-treasures": {
    slug: "mysterious-treasures",
    name: "Mysterious Treasures",
    series: "diamond-pearl",
    totalCards: 124,
    releaseDate: "2007/08/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "secret-wonders": {
    slug: "secret-wonders",
    name: "Secret Wonders",
    series: "diamond-pearl",
    totalCards: 132,
    releaseDate: "2007/11/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "great-encounters": {
    slug: "great-encounters",
    name: "Great Encounters",
    series: "diamond-pearl",
    totalCards: 106,
    releaseDate: "2008/02/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "majestic-dawn": {
    slug: "majestic-dawn",
    name: "Majestic Dawn",
    series: "diamond-pearl",
    totalCards: 100,
    releaseDate: "2008/05/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "legends-awakened": {
    slug: "legends-awakened",
    name: "Legends Awakened",
    series: "diamond-pearl",
    totalCards: 146,
    releaseDate: "2008/08/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "stormfront": {
    slug: "stormfront",
    name: "Stormfront",
    series: "diamond-pearl",
    totalCards: 106,
    releaseDate: "2008/11/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "platinum-base": {
    slug: "platinum-base",
    name: "Platinum",
    series: "platinum",
    totalCards: 133,
    releaseDate: "2009/02/11",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "rising-rivals": {
    slug: "rising-rivals",
    name: "Rising Rivals",
    series: "platinum",
    totalCards: 120,
    releaseDate: "2009/05/16",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "supreme-victors": {
    slug: "supreme-victors",
    name: "Supreme Victors",
    series: "platinum",
    totalCards: 153,
    releaseDate: "2009/08/19",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "arceus": {
    slug: "arceus",
    name: "Arceus",
    series: "platinum",
    totalCards: 111,
    releaseDate: "2009/11/04",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "black-white-base": {
    slug: "black-white-base",
    name: "Black & White",
    series: "black-white",
    totalCards: 115,
    releaseDate: "2011/04/25",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "emerging-powers": {
    slug: "emerging-powers",
    name: "Emerging Powers",
    series: "black-white",
    totalCards: 98,
    releaseDate: "2011/08/31",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "noble-victories": {
    slug: "noble-victories",
    name: "Noble Victories",
    series: "black-white",
    totalCards: 102,
    releaseDate: "2011/11/16",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "next-destinies": {
    slug: "next-destinies",
    name: "Next Destinies",
    series: "black-white",
    totalCards: 103,
    releaseDate: "2012/02/08",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "dark-explorers": {
    slug: "dark-explorers",
    name: "Dark Explorers",
    series: "black-white",
    totalCards: 111,
    releaseDate: "2012/05/09",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "dragons-exalted": {
    slug: "dragons-exalted",
    name: "Dragons Exalted",
    series: "black-white",
    totalCards: 128,
    releaseDate: "2012/08/15",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "dragon-vault": {
    slug: "dragon-vault",
    name: "Dragon Vault",
    series: "black-white",
    totalCards: 21,
    releaseDate: "2012/10/05",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "boundaries-crossed": {
    slug: "boundaries-crossed",
    name: "Boundaries Crossed",
    series: "black-white",
    totalCards: 153,
    releaseDate: "2012/11/07",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "plasma-storm": {
    slug: "plasma-storm",
    name: "Plasma Storm",
    series: "black-white",
    totalCards: 138,
    releaseDate: "2013/02/06",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "plasma-freeze": {
    slug: "plasma-freeze",
    name: "Plasma Freeze",
    series: "black-white",
    totalCards: 122,
    releaseDate: "2013/05/08",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "plasma-blast": {
    slug: "plasma-blast",
    name: "Plasma Blast",
    series: "black-white",
    totalCards: 105,
    releaseDate: "2013/08/14",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "legendary-treasures": {
    slug: "legendary-treasures",
    name: "Legendary Treasures",
    series: "black-white",
    totalCards: 140,
    releaseDate: "2013/11/06",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "xy-base": {
    slug: "xy-base",
    name: "XY",
    series: "xy",
    totalCards: 146,
    releaseDate: "2014/02/05",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "flashfire": {
    slug: "flashfire",
    name: "Flashfire",
    series: "xy",
    totalCards: 110,
    releaseDate: "2014/05/07",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "furious-fists": {
    slug: "furious-fists",
    name: "Furious Fists",
    series: "xy",
    totalCards: 114,
    releaseDate: "2014/08/13",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "phantom-forces": {
    slug: "phantom-forces",
    name: "Phantom Forces",
    series: "xy",
    totalCards: 124,
    releaseDate: "2014/11/05",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "primal-clash": {
    slug: "primal-clash",
    name: "Primal Clash",
    series: "xy",
    totalCards: 164,
    releaseDate: "2015/02/04",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "roaring-skies": {
    slug: "roaring-skies",
    name: "Roaring Skies",
    series: "xy",
    totalCards: 112,
    releaseDate: "2015/05/06",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "ancient-origins": {
    slug: "ancient-origins",
    name: "Ancient Origins",
    series: "xy",
    totalCards: 100,
    releaseDate: "2015/08/12",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "breakthrough": {
    slug: "breakthrough",
    name: "BREAKthrough",
    series: "xy",
    totalCards: 165,
    releaseDate: "2015/11/04",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "breakpoint": {
    slug: "breakpoint",
    name: "BREAKpoint",
    series: "xy",
    totalCards: 126,
    releaseDate: "2016/02/03",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "generations": {
    slug: "generations",
    name: "Generations",
    series: "xy",
    totalCards: 117,
    releaseDate: "2016/02/22",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "fates-collide": {
    slug: "fates-collide",
    name: "Fates Collide",
    series: "xy",
    totalCards: 129,
    releaseDate: "2016/05/02",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "steam-siege": {
    slug: "steam-siege",
    name: "Steam Siege",
    series: "xy",
    totalCards: 116,
    releaseDate: "2016/08/03",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "evolutions": {
    slug: "evolutions",
    name: "Evolutions",
    series: "xy",
    totalCards: 113,
    releaseDate: "2016/11/02",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "sun-moon-base": {
    slug: "sun-moon-base",
    name: "Sun & Moon",
    series: "sun-moon",
    totalCards: 173,
    releaseDate: "2017/02/03",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "guardians-rising": {
    slug: "guardians-rising",
    name: "Guardians Rising",
    series: "sun-moon",
    totalCards: 180,
    releaseDate: "2017/05/05",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "burning-shadows": {
    slug: "burning-shadows",
    name: "Burning Shadows",
    series: "sun-moon",
    totalCards: 177,
    releaseDate: "2017/08/05",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "crimson-invasion": {
    slug: "crimson-invasion",
    name: "Crimson Invasion",
    series: "sun-moon",
    totalCards: 126,
    releaseDate: "2017/11/03",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "ultra-prism": {
    slug: "ultra-prism",
    name: "Ultra Prism",
    series: "sun-moon",
    totalCards: 178,
    releaseDate: "2018/02/02",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "forbidden-light": {
    slug: "forbidden-light",
    name: "Forbidden Light",
    series: "sun-moon",
    totalCards: 150,
    releaseDate: "2018/05/04",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "celestial-storm": {
    slug: "celestial-storm",
    name: "Celestial Storm",
    series: "sun-moon",
    totalCards: 187,
    releaseDate: "2018/08/03",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "dragon-majesty": {
    slug: "dragon-majesty",
    name: "Dragon Majesty",
    series: "sun-moon",
    totalCards: 80,
    releaseDate: "2018/09/07",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "lost-thunder": {
    slug: "lost-thunder",
    name: "Lost Thunder",
    series: "sun-moon",
    totalCards: 240,
    releaseDate: "2018/11/02",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "team-up": {
    slug: "team-up",
    name: "Team Up",
    series: "sun-moon",
    totalCards: 198,
    releaseDate: "2019/02/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "detective-pikachu": {
    slug: "detective-pikachu",
    name: "Detective Pikachu",
    series: "sun-moon",
    totalCards: 18,
    releaseDate: "2019/04/05",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "unbroken-bonds": {
    slug: "unbroken-bonds",
    name: "Unbroken Bonds",
    series: "sun-moon",
    totalCards: 234,
    releaseDate: "2019/05/03",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "unified-minds": {
    slug: "unified-minds",
    name: "Unified Minds",
    series: "sun-moon",
    totalCards: 260,
    releaseDate: "2019/08/02",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "hidden-fates": {
    slug: "hidden-fates",
    name: "Hidden Fates",
    series: "sun-moon",
    totalCards: 69,
    releaseDate: "2019/08/23",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "cosmic-eclipse": {
    slug: "cosmic-eclipse",
    name: "Cosmic Eclipse",
    series: "sun-moon",
    totalCards: 272,
    releaseDate: "2019/11/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "sword-shield-base": {
    slug: "sword-shield-base",
    name: "Sword & Shield",
    series: "sword-shield",
    totalCards: 216,
    releaseDate: "2020/02/07",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "rebel-clash": {
    slug: "rebel-clash",
    name: "Rebel Clash",
    series: "sword-shield",
    totalCards: 209,
    releaseDate: "2020/05/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "darkness-ablaze": {
    slug: "darkness-ablaze",
    name: "Darkness Ablaze",
    series: "sword-shield",
    totalCards: 201,
    releaseDate: "2020/08/14",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "champions-path": {
    slug: "champions-path",
    name: "Champion's Path",
    series: "sword-shield",
    totalCards: 80,
    releaseDate: "2020/09/25",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "vivid-voltage": {
    slug: "vivid-voltage",
    name: "Vivid Voltage",
    series: "sword-shield",
    totalCards: 203,
    releaseDate: "2020/11/13",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "shining-fates": {
    slug: "shining-fates",
    name: "Shining Fates",
    series: "sword-shield",
    totalCards: 73,
    releaseDate: "2021/02/19",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "battle-styles": {
    slug: "battle-styles",
    name: "Battle Styles",
    series: "sword-shield",
    totalCards: 183,
    releaseDate: "2021/03/19",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "chilling-reign": {
    slug: "chilling-reign",
    name: "Chilling Reign",
    series: "sword-shield",
    totalCards: 233,
    releaseDate: "2021/06/18",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "evolving-skies": {
    slug: "evolving-skies",
    name: "Evolving Skies",
    series: "sword-shield",
    totalCards: 237,
    releaseDate: "2021/08/27",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "celebrations": {
    slug: "celebrations",
    name: "Celebrations",
    series: "sword-shield",
    totalCards: 25,
    releaseDate: "2021/10/08",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "fusion-strike": {
    slug: "fusion-strike",
    name: "Fusion Strike",
    series: "sword-shield",
    totalCards: 284,
    releaseDate: "2021/11/12",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "brilliant-stars": {
    slug: "brilliant-stars",
    name: "Brilliant Stars",
    series: "sword-shield",
    totalCards: 186,
    releaseDate: "2022/02/25",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "astral-radiance": {
    slug: "astral-radiance",
    name: "Astral Radiance",
    series: "sword-shield",
    totalCards: 216,
    releaseDate: "2022/05/27",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "pokemon-go": {
    slug: "pokemon-go",
    name: "Pokémon GO",
    series: "sword-shield",
    totalCards: 88,
    releaseDate: "2022/07/01",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "lost-origin": {
    slug: "lost-origin",
    name: "Lost Origin",
    series: "sword-shield",
    totalCards: 217,
    releaseDate: "2022/09/09",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "silver-tempest": {
    slug: "silver-tempest",
    name: "Silver Tempest",
    series: "sword-shield",
    totalCards: 215,
    releaseDate: "2022/11/11",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
  "crown-zenith": {
    slug: "crown-zenith",
    name: "Crown Zenith",
    series: "sword-shield",
    totalCards: 160,
    releaseDate: "2023/01/20",
    logo: "/placeholders/udsolgt.png",
    symbol: "/placeholders/udsolgt.png",
  },
};

export const sets: Record<string, PokemonSet> = {
  ...manualSets,
  ...generatedSets,
};

export default sets;
